services:
  - type: web
    name: edufund-backend
    env: node
    rootDir: backend
    plan: free
    buildCommand: npm install && npx prisma generate
    startCommand: npx prisma db push --accept-data-loss && npm run dev
    healthCheckPath: /api/health
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3001
      # Fill these in Render Dashboard or here if you prefer committing (not recommended)
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: SIGNER_PRIVATE_KEY
        sync: false
      - key: COMPANY_POOL_CONTRACT
        sync: false
      - key: MEZO_RPC
        value: https://rpc.test.mezo.org
    

